on:
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  container-tests:
    runs-on: ubuntu-latest
    name: "Secrets test for testing farm as a github action"

    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)

    steps:
      - name: Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      - name: Run the tests
        uses: ./
        with:
          api_key: ${{ secrets.TF_PUBLIC_API_KEY }}
          tmt_plan_regex: "secrets_plan"
          pull_request_status_name: "Secrets test"
          secrets: ${{ secrets.TF_SECRETS }}
          update_pull_request_status: "true"
          create_issue_comment: "true"
